import { openai } from './openrouter'
import { buildAIPortfolioPrompt, buildSimplePortfolioPrompt, buildErrorFallbackPrompt } from './prompt-templates'
import { validateHTML, createFallbackHTML } from './html-validator'
import type { WebsiteAnalysis } from './website-analyzer'
import type { MultiDeviceScreenshots } from './multi-device-screenshot'
import { tempImageStorage, type TempImageInfo } from './temp-image-storage'

// Enhanced website analysis interface for AI prompts
export interface EnhancedWebsiteAnalysis extends WebsiteAnalysis {
    visualElements?: {
        colorScheme: string[]
        typography: string
        layoutStyle: string
        visualHierarchy: string
    }
    responsiveFeatures?: {
        mobileOptimized: boolean
        tabletOptimized: boolean
        accessibilityScore: number
    }
}

// Main function to generate AI portfolio HTML
export async function generateAIPortfolioHTML(
    websiteData: EnhancedWebsiteAnalysis,
    screenshots: MultiDeviceScreenshots,
    options?: {
        style?: 'modern' | 'professional' | 'creative' | 'minimal'
        quality?: 'high' | 'medium' | 'low'
        includeMobile?: boolean
        includeTablet?: boolean
    }
): Promise<string> {
    let tempImages: Record<string, TempImageInfo> = {}

    try {
        if (!openai) {
            throw new Error('OpenRouter API key is not configured')
        }

        console.log('Generating AI portfolio HTML...')
        console.log('Options received:', options)

        // Save screenshots to temporary storage and get URLs
        console.log('Saving screenshots to temporary storage...')
        tempImages = await saveScreenshotsToTemp(screenshots, options)
        console.log('Temporary image URLs:', Object.keys(tempImages).map(key => `${key}: ${tempImages[key].url}`))

        // Test if images are accessible
        for (const [key, imageInfo] of Object.entries(tempImages)) {
            try {
                const response = await fetch(imageInfo.url)
                if (response.ok) {
                    console.log(`✅ ${key} image accessible: ${imageInfo.url}`)
                } else {
                    console.warn(`⚠️ ${key} image not accessible: ${imageInfo.url} (${response.status})`)
                }
            } catch (error) {
                console.error(`❌ ${key} image fetch error:`, error)
            }
        }

        // Generate a dynamic prompt using AI with image URLs
        const dynamicPrompt = await generateDynamicPrompt(websiteData, tempImages, options)
        console.log('Dynamic prompt length:', dynamicPrompt.length)
        console.log('Dynamic prompt preview:', dynamicPrompt.substring(0, 500) + '...')

        // Check prompt length (OpenRouter has limits)
        if (dynamicPrompt.length > 32000) {
            console.warn('Dynamic prompt too long, using simplified version')
            return await generateSimplePortfolioHTML(websiteData, tempImages.desktop?.url ?? '', options)
        }

        const response = await openai.chat.completions.create({
            model: 'anthropic/claude-3.5-sonnet',
            messages: [
                {
                    role: 'user',
                    content: dynamicPrompt
                }
            ],
            max_tokens: 4000,
            temperature: 0.9 // Higher temperature for more creative variations
        })

        const htmlContent = response.choices?.[0]?.message?.content
        if (!htmlContent) {
            throw new Error('No HTML content generated by AI')
        }

        console.log('AI HTML generated, validating...')
        console.log('Generated HTML preview:', htmlContent.substring(0, 500) + '...')

        // Check if the HTML contains image tags
        const hasImageTags = htmlContent.includes('<img') || htmlContent.includes('<image')
        console.log(`HTML contains image tags: ${hasImageTags}`)

        // Check if the HTML contains the screenshot URLs
        const hasScreenshotUrls = Object.values(tempImages).some(img => htmlContent.includes(img.url))
        console.log(`HTML contains screenshot URLs: ${hasScreenshotUrls}`)

        if (!hasImageTags) {
            console.warn('⚠️ Generated HTML does not contain image tags!')
        }
        if (!hasScreenshotUrls) {
            console.warn('⚠️ Generated HTML does not contain screenshot URLs!')
        }

        // Validate and optimize the generated HTML
        const validatedHTML = validateHTML(htmlContent)

        console.log('AI HTML validation complete')
        return validatedHTML

    } catch (error) {
        console.error('Error generating AI HTML:', error)

        // Fallback to simple prompt
        try {
            console.log('Attempting fallback with simple prompt...')
            return await generateSimplePortfolioHTML(websiteData, tempImages.desktop?.url ?? '', options)
        } catch (fallbackError) {
            console.error('Fallback also failed:', fallbackError)

            // Final fallback to static template
            return createFallbackHTML(
                websiteData.websiteData.title || 'Portfolio Website',
                websiteData.websiteData.url,
                tempImages.desktop?.url ?? ''
            )
        }
    } finally {
        // Clean up temporary images after a delay to allow AI processing
        if (Object.keys(tempImages).length > 0) {
            setTimeout(() => {
                void (async () => {
                    try {
                        const imageInfos = Object.values(tempImages)
                        await tempImageStorage.deleteMultipleImages(imageInfos)
                        console.log('Cleaned up temporary images after delay')
                    } catch (cleanupError) {
                        console.error('Error cleaning up temporary images:', cleanupError)
                    }
                })()
            }, 60000) // Wait 60 seconds before cleanup
        }
    }
}

// Fallback function using simpler prompt
async function generateSimplePortfolioHTML(
    websiteData: WebsiteAnalysis,
    screenshotUrl: string,
    options?: {
        style?: 'modern' | 'professional' | 'creative' | 'minimal'
        quality?: 'high' | 'medium' | 'low'
        includeMobile?: boolean
        includeTablet?: boolean
    }
): Promise<string> {
    if (!openai) {
        throw new Error('OpenRouter API key is not configured')
    }

    const prompt = buildSimplePortfolioPrompt(websiteData, screenshotUrl, options)

    // Check prompt length
    if (prompt.length > 32000) {
        console.warn('Simple prompt also too long, using fallback template')
        return createFallbackHTML(
            websiteData.websiteData.title || 'Portfolio Website',
            websiteData.websiteData.url,
            screenshotUrl
        )
    }

    try {
        const response = await openai.chat.completions.create({
            model: 'anthropic/claude-3.5-sonnet',
            messages: [
                {
                    role: 'user',
                    content: prompt
                }
            ],
            max_tokens: 2000,
            temperature: 0.5
        })

        const htmlContent = response.choices?.[0]?.message?.content
        if (!htmlContent) {
            throw new Error('No HTML content generated by AI')
        }

        return validateHTML(htmlContent)
    } catch (error) {
        console.error('Simple prompt generation failed:', error)
        throw error
    }
}

// Function to generate error state HTML
export async function generateErrorHTML(
    url: string,
    errorMessage: string
): Promise<string> {
    try {
        if (!openai) {
            throw new Error('OpenRouter API key is not configured')
        }

        const prompt = buildErrorFallbackPrompt(url, errorMessage)

        const response = await openai.chat.completions.create({
            model: 'anthropic/claude-3.5-sonnet',
            messages: [
                {
                    role: 'user',
                    content: prompt
                }
            ],
            max_tokens: 1000,
            temperature: 0.3
        })

        const htmlContent = response.choices[0]?.message?.content
        if (!htmlContent) {
            throw new Error('No HTML content generated by AI')
        }

        return validateHTML(htmlContent)

    } catch (error) {
        console.error('Error generating error HTML:', error)

        // Fallback to static error template
        return createFallbackHTML(
            'Error Loading Website',
            url,
            undefined
        )
    }
}

// Function to save screenshots to temporary storage
async function saveScreenshotsToTemp(
    screenshots: MultiDeviceScreenshots,
    options?: {
        includeMobile?: boolean
        includeTablet?: boolean
    }
): Promise<Record<string, TempImageInfo>> {
    const imagesToSave: Record<string, string> = {
        desktop: screenshots.desktop
    }

    if (options?.includeMobile && screenshots.mobile) {
        imagesToSave.mobile = screenshots.mobile
    }

    if (options?.includeTablet && screenshots.tablet) {
        imagesToSave.tablet = screenshots.tablet
    }

    return await tempImageStorage.saveMultipleImages(imagesToSave)
}

// Function to generate dynamic prompt using AI
async function generateDynamicPrompt(
    websiteData: EnhancedWebsiteAnalysis,
    tempImages: Record<string, TempImageInfo>,
    options?: {
        style?: 'modern' | 'professional' | 'creative' | 'minimal'
        quality?: 'high' | 'medium' | 'low'
        includeMobile?: boolean
        includeTablet?: boolean
    }
): Promise<string> {
    if (!openai) {
        throw new Error('OpenRouter API key is not configured')
    }

    const style = options?.style ?? 'modern'
    const quality = options?.quality ?? 'high'
    const includeMobile = options?.includeMobile ?? false
    const includeTablet = options?.includeTablet ?? false

    const promptGeneratorPrompt = `You are an expert prompt engineer. Create a VERY CONCISE prompt for generating a portfolio card HTML.

**CRITICAL: The final prompt MUST be under 25,000 characters total (including screenshots).**

**Requirements:**
- Style: ${style.toUpperCase()} (${getStyleDescription(style)})
- Quality: ${quality.toUpperCase()}
- Devices: ${includeMobile ? 'Include mobile screenshot' : 'Desktop only'}${includeTablet ? ', Include tablet screenshot' : ''}
- Output: 1200x675px portfolio card HTML
- Screenshots available: Desktop${includeMobile ? ', Mobile' : ''}${includeTablet ? ', Tablet' : ''}

**Website Info:**
- Title: ${websiteData.websiteData.title || 'Portfolio'}
- URL: ${websiteData.websiteData.url}
- Category: ${websiteData.analysis.category || 'General'}
- Purpose: ${websiteData.analysis.purpose || 'Portfolio'}
- Description: ${websiteData.websiteData.description || 'Personal portfolio website'}

**Task:** Create a prompt that will generate a ${style} portfolio card HTML for THIS SPECIFIC WEBSITE. The prompt should be EXTREMELY CONCISE - under 1000 characters for your part (screenshots will be added separately).

**CRITICAL:** The portfolio card must showcase THIS ACTUAL WEBSITE, not a generic project. Use the real title, description, and purpose.

Focus on the essential requirements only. Be direct and brief.

Return ONLY the prompt, no explanations.`

    try {
        const response = await openai.chat.completions.create({
            model: 'anthropic/claude-3.5-sonnet',
            messages: [
                {
                    role: 'user',
                    content: promptGeneratorPrompt
                }
            ],
            max_tokens: 1000,
            temperature: 0.3
        })

        const generatedPrompt = response.choices?.[0]?.message?.content
        if (!generatedPrompt) {
            throw new Error('No prompt generated by AI')
        }

        // Add the image URLs to the generated prompt
        let finalPrompt = `${generatedPrompt}

**CRITICAL: You MUST include these screenshots in your HTML output!**

**Screenshots to include:**
Desktop: ${tempImages.desktop?.url ?? 'Not available'}
${includeMobile && tempImages.mobile ? `Mobile: ${tempImages.mobile.url}` : ''}
${includeTablet && tempImages.tablet ? `Tablet: ${tempImages.tablet.url}` : ''}

**CRITICAL CONTENT REQUIREMENTS:**
- Use the REAL website title: "${websiteData.websiteData.title || 'Portfolio'}"
- Use the REAL website description: "${websiteData.websiteData.description || 'Personal portfolio website'}"
- Use the REAL website URL: "${websiteData.websiteData.url}"
- Use the REAL website purpose: "${websiteData.analysis.purpose || 'Portfolio'}"
- DO NOT create generic content - use the actual website data provided above

**IMPORTANT INSTRUCTIONS:**
- Use <img> tags to display the screenshots in your HTML
- Desktop screenshot should be the main hero image
- Mobile/tablet screenshots should be displayed in device frames
- Make sure all images are properly sized and positioned
- Include the screenshots as visual elements in your portfolio card
- Generate CLEAN, PROFESSIONAL HTML with modern CSS
- Use CSS variables for colors and consistent styling
- Add hover effects and smooth transitions
- Make it look like a premium portfolio card
- DO NOT include any markdown formatting or code comments

Return ONLY the complete HTML document with embedded CSS.`

        // Check if the final prompt is too long and optimize if needed
        if (finalPrompt.length > 30000) {
            console.warn(`Prompt too long (${finalPrompt.length} chars), optimizing...`)

            // Create a minimal prompt if it's still too long
            finalPrompt = `Create 1200x675px ${style.toUpperCase()} portfolio card HTML for THIS SPECIFIC WEBSITE.

**CRITICAL: Style=${style.toUpperCase()}, Quality=${quality}**
**Devices: ${includeMobile ? 'mobile' : ''}${includeMobile && includeTablet ? '+' : ''}${includeTablet ? 'tablet' : ''}**

**REAL WEBSITE DATA (USE THESE EXACTLY):**
- Title: "${websiteData.websiteData.title || 'Portfolio'}"
- Description: "${websiteData.websiteData.description || 'Personal portfolio website'}"
- URL: "${websiteData.websiteData.url}"
- Purpose: "${websiteData.analysis.purpose || 'Portfolio'}"
- Category: "${websiteData.analysis.category || 'General'}"

**CRITICAL: You MUST include these screenshots in your HTML!**

**Screenshots to include:**
Desktop: ${tempImages.desktop?.url ?? 'Not available'}
${includeMobile && tempImages.mobile ? `Mobile: ${tempImages.mobile.url}` : ''}
${includeTablet && tempImages.tablet ? `Tablet: ${tempImages.tablet.url}` : ''}

**IMPORTANT:**
- Use <img> tags to display the screenshots
- Desktop screenshot should be the main hero image
- Mobile/tablet screenshots should be in device frames
- Include all screenshots as visual elements
- Generate CLEAN, PROFESSIONAL HTML with modern CSS
- Use CSS variables for colors and consistent styling
- Add hover effects and smooth transitions
- Make it look like a premium portfolio card
- DO NOT include any markdown formatting or code comments
- DO NOT create generic content - use the real website data above

Requirements: ${style.toUpperCase()} styling, modern CSS, professional layout.
Return ONLY complete HTML with embedded CSS.`
        }

        console.log(`Final prompt length: ${finalPrompt.length} characters`)
        return finalPrompt
    } catch (error) {
        console.error('Error generating dynamic prompt:', error)
        // Fallback to simple prompt
        return `Create 1200x675px ${style.toUpperCase()} portfolio card HTML.

**CRITICAL: Style=${style.toUpperCase()}, Quality=${quality}**
**Devices: ${includeMobile ? 'mobile' : ''}${includeMobile && includeTablet ? '+' : ''}${includeTablet ? 'tablet' : ''}**

Website: ${websiteData.websiteData.title || 'Portfolio'} (${websiteData.websiteData.url})

**Screenshots:**
Desktop: ${tempImages.desktop?.url ?? 'Not available'}
${includeMobile && tempImages.mobile ? `Mobile: ${tempImages.mobile.url}` : ''}
${includeTablet && tempImages.tablet ? `Tablet: ${tempImages.tablet.url}` : ''}

Requirements: ${style.toUpperCase()} styling, modern CSS, professional layout.
Return ONLY complete HTML with embedded CSS.`
    }
}

// Helper function to get style descriptions
function getStyleDescription(style: string): string {
    switch (style) {
        case 'modern': return 'clean, minimalist, glassmorphism effects'
        case 'professional': return 'corporate, formal, structured layout'
        case 'creative': return 'bold, artistic, vibrant colors'
        case 'minimal': return 'ultra-clean, maximum whitespace'
        default: return 'clean, modern design'
    }
}

// Function to test AI generation with a simple prompt
export async function testAIGeneration(): Promise<boolean> {
    try {
        if (!openai) {
            console.error('OpenRouter API key is not configured')
            return false
        }

        const testPrompt = 'Create a simple HTML page with "Hello World" in a 1200x675px container. Return only the HTML.'

        const response = await openai.chat.completions.create({
            model: 'anthropic/claude-3.5-sonnet',
            messages: [
                {
                    role: 'user',
                    content: testPrompt
                }
            ],
            max_tokens: 500,
            temperature: 0.1
        })

        const htmlContent = response.choices?.[0]?.message?.content
        return !!htmlContent && htmlContent.includes('Hello World')

    } catch (error) {
        console.error('AI generation test failed:', error)
        return false
    }
}

// Function to get AI model information
export function getAIModelInfo(): {
    isConfigured: boolean
    model: string
    maxTokens: number
} {
    return {
        isConfigured: !!openai,
        model: 'anthropic/claude-3.5-sonnet',
        maxTokens: 4000
    }
} 